version: "3"

services:
  app:
    build: ./App
    container_name: "Flask_App"
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./App/app.py:/var/app/app.py
      - ./App/templates:/var/app/templates/

  db:
    image: mysql:5.7
    container_name: "MySQL_Database"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/:ro
